services:
  flaskagain_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  flaskagain_app:
    image: flaskagain
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - flaskagain_database
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg://app_user:app_password@flaskagain_database:5432/app_db

volumes:
  pgdata:
