# fly.toml app configuration file generated for nbilbo on 2024-12-04T13:21:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nbilbo'
primary_region = 'gig'

[build]

[[mounts]]
  source = 'nbilbo_data'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
